name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-${{ runner.os }}-

      - name: Set up Maven
        run: |
          echo "MAVEN_OPTS=--add-opens java.base/java.lang=ALL-UNNAMED" >> $GITHUB_ENV

      - name: Run SonarQube Scan
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=calcmvnsample \
            -Dsonar.host.url=http://192.168.9.22:9099/ \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
